name: PlanNUS CI

on:
  push:
    branches: [ "SATSolverAltSolnFix" ]
  pull_request:
    branches: [ "SATSolverAltSolnFix" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Create file
      run: cat /home/runner/work/TheGrumpyNUSFreshman/TheGrumpyNUSFreshman/PlanNUS/app/google-services.json | base64
    - name: Putting data
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA | base64 --decode > /home/runner/work/TheGrumpyNUSFreshman/TheGrumpyNUSFreshman/PlanNUS/app/google-services.json
    - name: Grant execute permission for gradlew
      run: cd PlanNUS && ls && chmod +x gradlew
    - name: Build with Gradle
      run: cd PlanNUS && ./gradlew build
    - name: Upload APK
      uses: actions/upload-artifact@v3.1.0
      with:
        name: PlanNUS app
        path: PlanNUS/app/build/outputs/apk/debug/app-debug.apk
