name: PlanNUS CI

on:
  push:
    branches: [ "SATSolverAltSolnFix" ]
  pull_request:
    branches: [ "SATSolverAltSolnFix" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        name: Checkout PlanNUS
        path: PlanNUS
    - name: set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        path: PlanNUS
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x PlanNUS/gradlew
    - name: Build with Gradle
      run: ./PlanNUS/gradlew build
    - name: Upload APK
      uses: actions/upload-artifact@v3.1.0
      with:
        name: PlanNUS app
        path: PlanNUS/app/build/outputs/apk/debug/app-debug.apk
